name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "."
          target: ${{secrets.PROJECT_PATH}}

      - name: Deploying to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd ~ && cd ${{secrets.PROJECT_PATH}} && git checkout master && git branch --set-upstream-to=origin/master master && git pull && cd app && npm run build-pro && cd .. && pm2 start ecosystem.config.js
